// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6EjzuFFm4WU_SeyYwEN0vZHZkI9D3R-Y',
    appId: '1:376675637142:web:019a0ac6d91f4d7e1aafb7',
    messagingSenderId: '376675637142',
    projectId: 'beans-test-app-123',
    authDomain: 'beans-test-app-123.firebaseapp.com',
    storageBucket: 'beans-test-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JlC6wW9YhOgCpYE904goKF3t5o3RW20',
    appId: '1:376675637142:android:ea0a6e85b14f0f2a1aafb7',
    messagingSenderId: '376675637142',
    projectId: 'beans-test-app-123',
    storageBucket: 'beans-test-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJlljbh_pFDvZy5WN0VIL7iCQoGJUWoto',
    appId: '1:376675637142:ios:f80adfb07a2b46891aafb7',
    messagingSenderId: '376675637142',
    projectId: 'beans-test-app-123',
    storageBucket: 'beans-test-app-123.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJlljbh_pFDvZy5WN0VIL7iCQoGJUWoto',
    appId: '1:376675637142:ios:f80adfb07a2b46891aafb7',
    messagingSenderId: '376675637142',
    projectId: 'beans-test-app-123',
    storageBucket: 'beans-test-app-123.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6EjzuFFm4WU_SeyYwEN0vZHZkI9D3R-Y',
    appId: '1:376675637142:web:029e329e0cd6460a1aafb7',
    messagingSenderId: '376675637142',
    projectId: 'beans-test-app-123',
    authDomain: 'beans-test-app-123.firebaseapp.com',
    storageBucket: 'beans-test-app-123.firebasestorage.app',
  );
}
